packages:
  - apps/*
  - packages/*
catalog:
  '@neondatabase/serverless': ^0.10.1
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0
  '@types/bun': ^1.1.12
  '@types/uuid': ^10.0.0
  '@typescript-eslint/eslint-plugin': ^7.1.0
  '@typescript-eslint/parser': ^7.1.0
  arctic: ^2.0.1
  dotenv: ^16.4.5
  drizzle-kit: ^0.26.2
  drizzle-orm: ^0.35.3
  eslint: ^8
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.1.2
  eslint-plugin-only-warn: ^1.1.0
  hono: ^4.6.6
  turbo: ^2.2.3
  uuid: ^10.0.0
  typescript: ^5.6.3
  prettier: ^3.3.3
