packages:
  - apps/*
  - packages/*
catalog:
  '@neondatabase/serverless': ^0.10.1
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0
  '@types/bun': ^1.1.16
  '@types/uuid': ^10.0.0
  '@typescript-eslint/eslint-plugin': ^7.1.0
  '@typescript-eslint/parser': ^7.1.0
  arctic: ^2.0.1
  dotenv: ^16.4.5
  drizzle-kit: ^0.30.1
  drizzle-orm: ^0.38.3
  eslint: ^8
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.1.2
  eslint-plugin-only-warn: ^1.1.0
  hono: ^4.6.6
  motion: ^11.11.17
  turbo: ^2.2.3
  uuid: ^10.0.0
  typescript: ^5.6.3
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
catalogs:
  # react19:
  #   '@types/react': npm:types-react-dom@rc
  #   '@types/react-dom': npm:types-react-dom@rc
  #   react: 19.0.0-rc-603e6108-20241029
  #   react-dom: 19.0.0-rc-603e6108-20241029
  #   next: 15.0.2
  #   eslint-config-next: 15.0.2
  react18:
    '@types/react': ^18
    '@types/react-dom': ^18
    react: ^18
    react-dom: ^18
    next: 14.2.23
    eslint-config-next: 14.2.23
