name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to git
        run: |
          git pull
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          architecture: 'x64'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Determine next version
        id: next_version
        run: |
          NEW_VERSION=$(pnpm release --ci --release-version | tail -n1)

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build @avelin/web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: |
            ghcr.io/avelinapp/web:latest
            ghcr.io/avelinapp/web:${{ steps.next_version.outputs.new_version }}
            ghcr.io/avelinapp/web:v${{ steps.next_version.outputs.new_version }}
          build-args: |
            NEXT_PUBLIC_APP_URL=https://avelin.app
            NEXT_PUBLIC_API_URL=https://api.avelin.app
            NEXT_PUBLIC_SYNC_URL=wss://sync.avelin.app
            NEXT_PUBLIC_POSTHOG_KEY=phc_ClqyvBT8tnlp26PQhvbWZHuSMvrn6gq0CZEqfzwI3JC
          platforms: linux/amd64,linux/arm64

      - name: Build @avelin/api
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/avelinapp/api:latest
            ghcr.io/avelinapp/api:${{ steps.next_version.outputs.new_version }}
            ghcr.io/avelinapp/api:v${{ steps.next_version.outputs.new_version }}
          platforms: linux/amd64,linux/arm64

      - name: Build @avelin/sync
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/sync/Dockerfile
          push: true
          tags: |
            ghcr.io/avelinapp/sync:latest
            ghcr.io/avelinapp/sync:${{ steps.next_version.outputs.new_version }}
            ghcr.io/avelinapp/sync:v${{ steps.next_version.outputs.new_version }}
          platforms: linux/amd64,linux/arm64

      - name: Build @avelin/migrate
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/database/Dockerfile
          push: true
          tags: |
            ghcr.io/avelinapp/migrate:latest
            ghcr.io/avelinapp/migrate:${{ steps.next_version.outputs.new_version }}
            ghcr.io/avelinapp/migrate:v${{ steps.next_version.outputs.new_version }}
          platforms: linux/amd64,linux/arm64

      - name: Checkout IaC repo
        uses: actions/checkout@v4
        with:
          repository: avelinapp/iac
          token: ${{ secrets.GH_IAC_SECRET }}
          fetch-depth: 0
          path: iac

      - name: Update K8s manifests in IaC repo
        working-directory: iac
        run: |
          VERSION=v${{ steps.next_version.outputs.new_version }}
          apps=("web" "api" "sync")
          manifests_dir="k8s"
          for app in "${apps[@]}"; do
            manifest="$manifests_dir/${app}-deploy.yaml"
            if [ -f "$manifest" ]; then
              echo "Updating image tag in $manifest to $VERSION"
              yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/$app:$VERSION\"" "$manifest"
            else
              echo "Manifest file $manifest not found!"
              exit 1
            fi
          done

          app="migrate"
          manifest="$manifests_dir/db-migration-job.yaml"
          if [ -f "$manifest" ]; then
            echo "Updating image tag in $manifest to $VERSION"
            yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/$app:$VERSION\"" "$manifest"
          else
            echo "Manifest file $manifest not found!"
            exit 1
          fi

      - name: Commit changes to IaC repo
        working-directory: iac
        run: |
          git pull
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add .
          git commit -m "chore: update manifests to v${{ steps.next_version.outputs.new_version }}"
          git push

      - name: Create GitHub release
        run: |
          pnpm release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
